### ISSUE TITLE
How to sort results?

### ISSUE THREAD

**Issue by oleksify** [kidpollo/tanker#51]
Is there a way to sort results of search? I use indextank for e-commerce app for facet search & catalog list. I need to have the ability to sort by name in ASC & DESC orders,  and sort by (price \* product.currency.index). As results returned as paginated results I'm not able to sort them as array bevcause each page begins from the start. Paginate => false didn't work right now. Any ideas hot to accomplish this?

**Comment by kidpollo** [comment]
Search indexes work a little bit different form relational databases basically there are scoring functions for this.
Tanker does not provide a specific api for this because the way scoring functions and variables can vary a lot.
check out

http://indextank.com/documentation/function-definition

for more info.

About the pagination, as I addressed on the other thread it seems to be that IndexTank enforces a default of 10 so if you are willing to always return all results you should try setting a huge per page number but I would not recommend it.

There is an example on the tanker readme on how to use functions and variables for sorting Geospatial data.

Cheers
